# Generated by Django 5.2.4 on 2025-07-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='profile_banners/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
            options={
                'verbose_name': 'ProfileModel',
                'verbose_name_plural': 'ProfileModels',
                'db_table': 'profile',
                'managed': True,
            },
        ),
    ]
