# Generated by Django 5.2.4 on 2025-07-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='banner',
            field=models.ImageField(default='default_banner.jpg/banner.jpg', upload_to='profile_banners/'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(default='default.jpg/user_photo.jpg', upload_to='profile_images/'),
        ),
    ]
