# Generated by Django 5.2.4 on 2025-07-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profilemodel_banner_alter_profilemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='banner',
            field=models.ImageField(default='profile_banners/default_banner.jpg', upload_to='profile_banners/'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
