# Generated by Django 5.2.4 on 2025-07-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profilemodel_bio_alter_profilemodel_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(default='profileImages/default.jpg', upload_to='profile_images/'),
        ),
    ]
